name: Test Publish Python Package

on:
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      id-token: write

    runs-on: ubuntu-latest
    environment: pypi-testing

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.5.24"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Build package
      run: uv build

    - name: Publish package
      run: uv publish
      env:
        UV_PUBLISH_CHECK_URL: "https://test.pypi.org/simple/"
        UV_PUBLISH_URL: "https://test.pypi.org/legacy/"
